export const defaultProducts = [
  {
    id: "plain-frosted-6x8",
    title: "6 X 8 Inch Plain Frosted Zipper Bags",
    image: "/products/product-frosted-plain.svg",
    original: 23.28,
    price: 19.4,
    kind: "standard",
    featured: true,
  },
  {
    id: "plain-frosted-14x18",
    title: "14 X 18 Inch Plain Frosted Zipper Bags",
    image: "/products/product-frosted-plain.svg",
    original: 31.9,
    price: 26.55,
    kind: "standard",
    featured: true,
  },
  {
    id: "plain-frosted-10x12",
    title: "10 X 12 Inch Plain Frosted Zipper Bags",
    image: "/products/product-frosted-plain.svg",
    original: 27.75,
    price: 22.8,
    kind: "standard",
    featured: true,
  },
  {
    id: "plain-frosted-8x10",
    title: "8 X 10 Inch Plain Frosted Zipper Bags",
    image: "/products/product-frosted-plain.svg",
    original: 25.4,
    price: 20.9,
    kind: "standard",
    featured: true,
  },
  {
    id: "custom-frosted-slider",
    title: "Custom Printed Frosted Slider Bags",
    image: "/products/product-frosted-printed.svg",
    original: 44.0,
    price: 36.9,
    kind: "custom",
    rating: 5,
    href: "/product/custom-printed-frosted-slider-zipper-lock-bags",
    featured: true,
  },
  {
    id: "custom-pink-courier",
    title: "Custom Printed Pink Courier Bags",
    image: "/products/info-pink-pretty.svg",
    original: 52.0,
    price: 41.0,
    kind: "custom",
    rating: 5,
    href: "/product/custom-printed-pink-courier-bags-60-micron",
    featured: true,
  },
  {
    id: "custom-purple-courier",
    title: "Custom Printed Purple Courier Bags",
    image: "/products/info-purple-hey.svg",
    original: 52.0,
    price: 41.0,
    kind: "custom",
    rating: 5,
    href: "/product/custom-printed-purple-courier-bags-60-micron",
    featured: true,
  },
  {
    id: "custom-white-courier",
    title: "Custom Printed White Courier Bags",
    image: "/products/info-white-floral.svg",
    original: 52.0,
    price: 41.0,
    kind: "custom",
    rating: 5,
    href: "/product/custom-printed-white-courier-bags-51-micron",
    featured: true,
  },
  {
    id: "custom-black-courier",
    title: "Custom Printed Black Courier Bags",
    image: "/products/info-black-ribbon.svg",
    original: 52.0,
    price: 41.0,
    kind: "custom",
    rating: 5,
    href: "/product/custom-printed-black-courier-covers-60-micron",
    featured: true,
  },
  // Category listing images (Custom Printed Courier Bags page)
  {
    id: "custom-printed-white",
    title: "Custom Printed White Courier Bag",
    image: "/products/custom-printed-white.svg",
    original: 0,
    price: 0,
    kind: "custom",
    href: "/product/custom-printed-white-courier-bags-51-micron",
    featured: false,
  },
  {
    id: "custom-printed-black",
    title: "Custom Printed Black Courier Bag",
    image: "/products/custom-printed-black.svg",
    original: 0,
    price: 0,
    kind: "custom",
    href: "/product/custom-printed-black-courier-covers-60-micron",
    featured: false,
  },
  {
    id: "custom-printed-pink",
    title: "Custom Printed Pink Courier Bag",
    image: "/products/custom-printed-pink.svg",
    original: 0,
    price: 0,
    kind: "custom",
    href: "/product/custom-printed-pink-courier-bags-60-micron",
    featured: false,
  },
  {
    id: "custom-printed-purple",
    title: "Custom Printed Purple Bag",
    image: "/products/custom-printed-purple.svg",
    original: 0,
    price: 0,
    kind: "custom",
    href: "/product/custom-printed-purple-courier-bags-60-micron",
    featured: false,
  },
];

